spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1314920xuewei
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181